Parser
ITMO-F-Team/F-Project pull request #8
Opened 2024-03-16 14:25 UTC by Furetur

2024-03-16 16:30 UTC, achains requested changes

2024-03-16 17:29 UTC, achains requested changes

2024-03-16 17:29 UTC, achains commented on src/flang/parse/parser.cpp
> +    return std::unique_ptr<IdentifierNode>{node};
std::make_unique

2024-03-16 17:29 UTC, achains commented on src/flang/parse/parser.cpp
> +    auto node = new ProgramNode(std::move(elements));
std::make_unique

2024-03-16 17:29 UTC, achains commented on src/flang/parse/parser.cpp
> +  auto parser = new Parser(tokens);
**Memleak** :) 
Why not `return Parser(tokens).parse_program()`?

2024-03-17 06:06 UTC, Furetur commented on src/flang/parse/parser.cpp
> +class Parser {
Because it's private. Nobody outside of parser.cpp should know that it exists

2024-03-20 19:32 UTC, merged